### ISSUE TITLE
Boostrap with Kendo Theme

### ISSUE THREAD

**Issue by tareknaj** [telerik/kendo-bootstrap-demo#3]
If I want to use Silver theme or other theme with bootstrap, is it necessary to include kendo.common-bootstrap.min.css ?
The documentation is not clear about this point http://docs.telerik.com/kendo-ui/using-kendo-with-twitter-bootstrap

**Comment by gyoshev** [comment]
In case this is still relevant: the common-bootstrap file is needed only by the bootstrap theme. For the silver theme, use kendo.common.css. 

You can post such questions via support tickets or forum threads, in order to get timely responses.
